# Generated by Django 5.0.7 on 2024-07-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookrecipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(default='', upload_to='recipe-images'),
        ),
    ]
