# Generated by Django 5.0.7 on 2024-08-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookrecipe', '0002_recipe_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(default='', upload_to='recipes/images'),
        ),
    ]
